name: Create environment

on:
  workflow_dispatch:
  push:
    branches-ignore: main

jobs:
 create:
   name: Create environment
   runs-on: ubuntu-latest
   environment:
    name: test
   steps:
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - uses: actions/checkout@v4
    
    - name: Restore tool
      run: |
        dotnet tool restore
        dotnet sitecore --version

    - name: Login to Sitecore XM Cloud
      shell: pwsh
      run: dotnet sitecore cloud login --client-id $env:CLI_USER --client-secret $env:CLI_PASS --non-interactive
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
        CLI_USER: ${{ secrets.XMCLOUD_CLIENTID }}
        CLI_PASS: ${{ secrets.XMCLOUD_CLIENTSECRET }}

    - name: Create environment
      shell: pwsh
      run: |
        $commitRef = "${{ github.ref }}"
        $projectId = $env:XMCLOUD_PROJECTID
        $envName = "test-{0}" -f ($commitRef.Split("/") | Select-Object -Last 1)

        $existingId = dotnet sitecore cloud environment list --project-id $projectId --json | ConvertFrom-Json | Where-Object { $_.name -eq $envName } | Select-Object -ExpandProperty id
        if($Null -eq $existingId) {
            dotnet sitecore cloud environment create --project-id $projectId --name $envName
        } else {
            Write-Host "Environment '${envName}' already exists"
        }
      env:
        XMCLOUD_PROJECTID: ${{ vars.XMCLOUD_PROJECTID }}
